services:
  - type: web
    name: rocket-rollout-api
    runtime: node
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && NODE_ENV=production node index.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: NODE_OPTIONS
        value: "--openssl-legacy-provider"
      - key: REACT_APP_API_URL
        sync: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
